source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails', '4.2.1'
gem 'pg', '~> 0.17.1'
gem 'aws-sdk', '~> 1.48.1'
gem 'figaro', '~> 1.1.1'
gem 'quiet_assets', '~> 1.1.0'

gem 'turbolinks', '~> 2.5.3'
gem 'jbuilder', '~> 2.2.16'
gem 'slim-rails', '~> 3.0.1'
gem 'sass-rails', '5.0'
gem 'compass-rails', '~> 2.0.4'
gem 'uglifier', '~> 2.7.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'react-rails', '~> 1.0.0'
gem 'jquery-rails', '~> 4.0.3'
gem 'jquery.fileupload-rails', '~> 1.11.0'
gem 'underscore-rails', '~> 1.8.3'
gem 'faraday', '~> 0.9.1'
gem 'multi_json', '~> 1.11.0'
gem 'kaminari', '~> 0.16.3'
gem 'bootstrap-kaminari-views', '~> 0.0.3'
gem 'hashie', '~> 3.2.0'
gem 'draper', '~> 1.3.1'
gem 'money', '~> 6.5.1'
gem 'js-routes', '~> 1.0.1'
gem 'bootstrap-sass', '~> 3.3.4.1'
gem 'bootswatch-rails', '~> 3.3.4'
gem 'nprogress-rails', '~> 0.1.6.7'
gem 'mimemagic', '~> 0.3.0'
gem 'pikaday-gem', '~> 1.2.0'
gem 'momentjs-rails', '~> 2.10.3'
gem 'gaffe', '~> 1.0.2'
gem 'font-awesome-rails', '~> 4.3.0.0'
gem 'formvalidation-rails', '~> 0.6.1.2'
gem 'chosen-rails', '~> 1.4.1'
gem 'pdfjs_viewer-rails', '~> 0.0.5'
gem 'd3-rails', '~> 3.5.5'
gem 'axlsx'

group 'development' do
  gem 'spring', '~> 1.3.6'
  gem 'spring-commands-rspec', '~> 1.0.4'
  gem 'guard-rspec', '~> 4.5.2'
  gem 'rb-fsevent', '~> 0.9.5'
  gem 'pry', '~> 0.10.1'
  gem 'better_errors', '~> 2.1.1'
  gem 'binding_of_caller', '~> 0.7.2'
end

group 'development', 'test' do
  gem 'rspec-rails', '~> 3.2.3'
end

gem 'unicorn', '~> 4.9.0'
gem 'rack-timeout', '~> 0.2.4'
gem 'rails_12factor', group: :production
gem 'browserify-rails', '~>0.5'
